### ISSUE TITLE
no ending in filename causes segfault

### ISSUE THREAD

**Issue by gdkrmr** [yihui/tikzDevice#118] opened 2015-08-01 08:35 UTC
```R
> library(tikzDevice)
> tikz("test")

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .External(TikZ_StartDevice, file, width, height, onefile, bg,     fg, baseSize, lwdUnit, standAlone, bareBones, documentDeclaration,     packages, footer, console, sanitize, engine, symbolicColors,     colorFileName, maxSymbolicColors, timestamp)
 2: tikz("test")
```
I think a simple error or automatic change to ```tikz("test.tex")``` with a warning would be in order here

**Comment by krlmlr** [comment] 2015-08-02 15:53
This sounds like a dupe of #101 and should be fixed in the development version.

**Closed** 2015-09-11 21:14 UTC
