### ISSUE TITLE
Error in getMetricsFromLatex(TeXMetrics)

### ISSUE THREAD

**Issue by aussetg** [yihui/tikzDevice#46] opened 2014-01-01 17:35 UTC
Mac OS X 10.9, Last Tikzdevice version, last Knitr version, XeLaTeX

> sessionInfo()
> R version 3.0.2 (2013-09-25)
> Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] devtools_1.4.1 digest_0.6.4   evaluate_0.5.1 httr_0.2       memoise_0.1    parallel_3.0.2 RCurl_1.95-4.1
 [8] stringr_0.6.2  tools_3.0.2    whisker_0.3-2 

---

 ==> Fatal error occurred, no output PDF file produced!
Quitting from lines 93-97 (Rapport.Rnw) 
Erreur dans getMetricsFromLatex(TeXMetrics) : 
TeX was unable to calculate metrics for the following string
or character:

```
grid[, 1]
```

Common reasons for failure include:
- The string contains a character which is special to LaTeX unless
  escaped properly, such as % or $.
- The string makes use of LaTeX commands provided by a package and
  the tikzDevice was not told to load the package.

The contents of the LaTeX log of the aborted run have been printed above,
it may contain additional details as to why the metric calculation failed.
Calls: knit ... widthDetails.text -> grid.Call -> <Anonymous> -> getMetricsFromLatex

Exécution arrêtée

**Comment by casallas** [comment] 2015-03-25 21:49
I was able to replicate this error with a different file that had
```latex
\usepackage[table]{xcolor}
```
in the preamble. Strangely using `xcolor` without the `table` option solved this issue! 
I also use `hyperref` in my preamble but that didn't seem to cause any issues.

**Comment by krlmlr** [comment] 2015-03-25 21:56
@tobi2185: Sorry, I missed that -- the `dvips` option for `hyperref` is clearly wrong, as `tikzDevice` uses pdflatex (or xelatex or lualatex, but no latex).

@casallas: Thanks. Would you like to share an example? Please also post your `sessionInfo()`.

**Comment by casallas** [comment] 2015-03-25 22:21
sure, this is the most minimal example I could think of

```latex
\documentclass{article}
\usepackage[T1]{fontenc}

\usepackage[table]{xcolor}

\begin{document}

<<dev="tikz">>=
library(ggplot2)
qplot(1)
@

\end{document}
```
This is my `sessionInfo()`
```
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin14.1.0 (64-bit)
Running under: OS X 10.10.2 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tikzDevice_0.8.1 ggplot2_1.0.0   

loaded via a namespace (and not attached):
 [1] colorspace_1.2-5 digest_0.6.8     evaluate_0.5.5   filehash_2.2-2  
 [5] formatR_1.0      grid_3.1.3       gtable_0.1.2     highr_0.4       
 [9] knitr_1.9        labeling_0.3     MASS_7.3-39      munsell_0.4.2   
[13] plyr_1.8.1       proto_0.3-10     Rcpp_0.11.5      reshape2_1.4.1  
[17] scales_0.2.4     stringr_0.6.2    tcltk_3.1.3      tools_3.1.3
```

And the knitr output is in this gist: https://gist.github.com/casallas/faa87f2aee256666a6fa

It may be worth noting that I'm using `MacTeX 2014`, and `xcolor v2.11 (2007/01/21)`

**Comment by casallas** [comment] 2015-03-25 22:24
just to recap removing the `table` option from `xcolor` makes the example work, i.e.,
```latex
\documentclass{article}
\usepackage[T1]{fontenc}

\usepackage{xcolor}

\begin{document}

<<dev="tikz">>=
library(ggplot2)
qplot(1)
@

\end{document}
```

**Comment by krlmlr** [comment] 2015-03-25 22:26
I can replicate this on my Ubuntu system. This is so weird. :+1: for tracking this down!

**Comment by krlmlr** [comment] 2015-03-25 22:44
@casallas: Please try adding `\PassOptionsToPackage{table}{xcolor}` in a separate line just before the `documentclass` declaration instead of specifying `[table]`. I have no idea if this option is then actually passed to the `xcolor` package.

@yihui: I'm afraid this might be a `knitr` issue after all. How about implementing something similar to #107 for `knitr`?

**Comment by casallas** [comment] 2015-03-25 23:07
worked like a charm! In any case I wasn't using table colors so I wasn't suffering from the lack of the `table` option in `xcolor` :)

**Comment by casallas** [comment] 2015-03-25 23:13
coming back to @aussetg's problem, even though I have 0 experience with XeLaTeX, using my minimal example I was able to track down the following problematic things in his preamble that knitr didn't like:

```latex
\documentclass{article}
% Uncomment any of the lines below to make knitr upset
%\usepackage{polyglossia}
%\setdefaultlanguage{french}
%\usepackage{fontspec} % Xelatex
%\usepackage{minted}

\begin{document}

<<dev="tikz">>=
library(ggplot2)
qplot(1)
@

\end{document}
```

generating the same problems as with `\usepackage[table]{xcolor}`!

**Comment by krlmlr** [comment] 2015-03-26 10:23
@casallas: Thanks a lot for your efforts. Any of the lines in the example above create an invalid preamble for *all* measurement runs of `tikzDevice`. For the user, it's difficult to deduce the true reason (malformed preamble) from the error message.

Now I think we need to add a first run with an (almost) empty document using whatever `tikzDevice` thinks should be the preamble. If this fails, we can produce a suitable error message. Let's discuss this further in #108.

**Comment by yihui** [comment] 2015-03-26 20:43
@krlmlr **knitr** adds `\usepackage{color}` to the preamble automatically, and that could be a problem, since @casallas wants to use **xcolor** instead.

**Comment by casallas** [comment] 2015-04-18 21:06
just a follow-up to @yihui's comment, using both `color` and `xcolor` seems to be problematic, indeed. You can either get latex warnings or, as shown above, errors. However, (from my understanding) `xcolor` supersedes `color`, so a hook can be used to replace the latter in `knitr`, such that

```latex
\begin{document}

<<setup, echo=FALSE, message=FALSE, warning=FALSE>>=
local({
  hook_document <- knitr::knit_hooks$get('document')
  knitr::knit_hooks$set(document = function(x){
    res <- hook_document(x)
    gsub('\\usepackage[]{color}', '\\usepackage[table]{xcolor}', res, fixed = T)
  })
})
@

<<dev="tikz">>=
library(ggplot2)
qplot(1)
@

\end{document}
```

If the table option is not necessary, just change the `gsub` line to 

`gsub('\\usepackage[]{color}', '\\usepackage[]{xcolor}', res, fixed = T)`

**Comment by leeper** [comment] 2015-06-11 18:09
A seemingly related issue has come up with the `beamerarticle` LaTeX package here: http://stackoverflow.com/questions/30697967/knitr-beamerarticle-dev-tikz

**Comment by adamliter** [comment] 2015-12-31 00:43
I can reproduce this error with the following MWE. *Without* `\usepackage{fontspec}`, it compiles just fine.

```tex
\documentclass{article}

\usepackage{fontspec}

\begin{document}

<<dev='tikz'>>=
library(ggplot2)
qplot(1)
@


\end{document}
```

Error message:

```
Quitting from lines 8-10 (asdf.Rnw)
Error in getMetricsFromLatex(TeXMetrics, verbose = verbose) :
TeX was unable to calculate metrics for the following string
or character:

	count

Common reasons for failure include:
  * The string contains a character which is special to LaTeX unless
    escaped properly, such as % or $.
  * The string makes use of LaTeX commands provided by a package and
    the tikzDevice was not told to load the package.

The contents of the LaTeX log of the aborted run have been printed above,
it may contain additional details as to why the metric calculation failed.
Calls: knit ... widthDetails.text -> grid.Call -> <Anonymous> -> getMetricsFromLatex

Execution halted
```

Output of `sessionInfo()`:

```
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.2 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.11

loaded via a namespace (and not attached):
[1] tools_3.2.3
```

**Comment by basp91** [comment] 2016-03-24 00:26
This worked for me. I added in R
`options(tikzMetricPackages = c("\\usepackage[utf8]{inputenc}","\\usepackage[T1]{fontenc}", "\\usetikzlibrary{calc}", "\\usepackage{amssymb}"))`

[source](http://freakonometrics.hypotheses.org/6290)

**Comment by clemlaflemme** [comment] 2016-10-17 11:55
I had a similar issue by simply adding 

```
\let\oldalltt\alltt
\let\oldendalltt\endalltt
\renewenvironment{alltt}{\setlength\topsep{0pt}\oldalltt}{\oldendalltt}
```

Note : I did that because I don't like the empty lines between `R input and output rendered by `knitr`. Is there another way to avoid them ?

**Comment by photopresentr** [comment] 2017-02-23 13:10
On Fedora 24, I encountered this problem and was able to fix it by installing the latex preview package:

`sudo dnf install tex-preview`

The error message could perhaps be made a bit more informative :)

**Comment by krlmlr** [comment] 2017-08-14 13:48
Fixed in #142. Now `tikzTest()` is an easier way to troubleshoot problems.

**Closed by krlmlr** 2017-08-14 13:48 UTC

**Comment by niklaas** [comment] 2017-12-28 14:52
I enountered the issue @casallas described: `\usepackage[table]{xcolor}` was responsible for the error.  Using`\PassOptionsToPackage{table}{xcolor}\usepackage{xcolor}` instead of `\usepackage{xcolor}` solved it.

**Comment by earcanal** [comment] 2020-05-06 12:25
Another similar data point. I resolved `Error in getMetricsFromLatex(TeXMetrics, verbose = verbose)` errors under:

    \usepackage[grumpy]{gitinfo2}

with

    \usepackage{gitinfo2}
    \PassOptionsToPackage{grumpy}{gitinfo2}
